language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libxml-checker-perl libdbd-pg-perl libperl-critic-perl libdevel-cover-perl
install:
- dotnet restore
script:
- dotnet build
- dotnet test PrayerBookDALTest/PrayerBookDALTest.csproj
- dotnet test PrayerBookBLLTest/PrayerBookBLLTest.csproj
branches:
  only:
  - master
  - development
  notifications:
  email: false