language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
install:
- dotnet restore
script:
- dotnet build
- dotnet test PrayerBookDALTest/PrayerBookDALTest.csproj
- dotnet test PrayerBookBLLTest/PrayerBookBLLTest.csproj
branches:
  only:
  - master
  - development
  notifications:
  email: false