language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
    - sudo rm -rf /etc/apt/sources.list.d/rwky-redis.list
    - sudo add-apt-repository ppa:chris-lea/redis-server -y
install:
- dotnet restore
script:
- dotnet build
- dotnet test PrayerBookDALTest/PrayerBookDALTest.csproj
- dotnet test PrayerBookBLLTest/PrayerBookBLLTest.csproj
branches:
  only:
  - master
  - development
  notifications:
  email: false