language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
before_install:
  # to bypass not being able to use apt-get.
  - sudo sed -i s/us.archive.ubuntu/old-releases.ubuntu/g /etc/apt/sources.list
  - sudo sed -i s/security.ubuntu/old-releases.ubuntu/g /etc/apt/sources.list
  - sudo apt-get update
install:
- dotnet restore
script:
- dotnet build
- dotnet test PrayerBookDALTest/PrayerBookDALTest.csproj
- dotnet test PrayerBookBLLTest/PrayerBookBLLTest.csproj
branches:
  only:
  - master
  - development
  notifications:
  email: false